apiVersion: v1
kind: Service
metadata:
  name: auth-service-20i-0999
  labels:
    app: auth
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 0999
      nodePort: 30097
  selector:
    app: auth
