apiVersion: v1
kind: Service
metadata:
  name: classrooms-service-20i-0999
  labels:
    app: classrooms
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 0999
      nodePort: 30096
  selector:
    app: classrooms
