apiVersion: apps/v1
kind: Deployment
metadata:
  name: classrooms-deployment-20i-0999
  labels:
    app: classrooms
spec:
  replicas: 3
  selector:
    matchLabels:
      app: classrooms
  template:
    metadata:
      labels:
        app: classrooms
    spec:
      containers:
      - name: classrooms
        image: your-dockerhub-username/classrooms:20i-0999
        ports:
        - containerPort: 0999
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /
            port: 0999
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 0999
          initialDelaySeconds: 15
          periodSeconds: 20
