apiVersion: v1
kind: Service
metadata:
  name: frontend-service-20i-0999
  labels:
    app: frontend
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 0999
      nodePort: 30099
  selector:
    app: frontend
