apiVersion: v1
kind: Service
metadata:
  name: post-service-20i-0999
  labels:
    app: post
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 0999
      nodePort: 30095
  selector:
    app: post
